services:
  exchange:
    build:
      context: .
      target: development
    command: npm run start:dev exchange
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${PORT:-8000}:${PORT:-8000}'

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - 'pg_data:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}'

volumes:
  pg_data:
