apiVersion: v1
kind: Secret
metadata:
  name: appSecret
type: Opaque
data:
  PORT: "8000"

  POSTGRES_PORT: ""
  POSTGRES_HOST: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_DB: ""

  EXCHANGE_RATE_BASE_URL: ""
  EXCHANGE_RATE_API_KEY: ""

  COINGATE_BASE_URL: ""